# Generated by Django 4.1.5 on 2023-01-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expression_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='songsdatabase',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expression_analyzer.emotions'),
        ),
    ]
