# Generated by Django 4.1.5 on 2023-01-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expression_analyzer', '0002_emotions_alter_songsdatabase_emotion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emotions',
            new_name='Emotion',
        ),
    ]
