# Generated by Django 4.1.5 on 2023-01-29 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expression_analyzer', '0003_rename_emotions_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsdatabase',
            name='link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
